name: solid_assignment
description: Refactored SOLID assignment with layered architecture and Flutter UI (presentation + domain only)
version: 0.2.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
  test: ^1.25.0

flutter:
  uses-material-design: true
